apiVersion: v1
kind: Service
metadata:
  name: alpaca-prod
  labels:
    app: alpaca
    ver: '1'
    env: prod
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: alpaca