apiVersion: apps/v1
kind: Deployment
metadata:
  name: bandicoot-prod
  labels:
    app: bandicoot
    ver: '2'
    env: prod
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bandicoot
  template:
    metadata:
      labels:
        app: bandicoot
    spec:
      containers:
        - name: bandicoot-prod
          image: gcr.io/kuar-demo/kuard-amd64:green
          readinessProbe:
            httpGet:
              path: /ready
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 2
            successThreshold: 1
            failureThreshold: 3
          ports:
            - containerPort: 8080